export default [
  {
    id: 1,
    postedOn: new Date(),
    title: "Delivery Executive",
    type: "Full time",
    location: "Mumbai",
    experience: "Fresher",
    education: "Graduate",
    companyName: "Shadowfax",
    companyUrl: "shadowfax.com",
    salary: "Rs.25000 - Rs.30000",
    skills: ["Communication", "Driving"],
    link: "https://shadowfax.com/careers",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "Credit Card Sales",
    type: "Part time",
    location: "Pune",
    experience: "1-2 Years",
    education: "12th Grade",
    companyName: "CounterRec",
    companyUrl: "counterrec.com",
    salary: "Rs.12000 - Rs.15000",
    skills: ["Communication", "English"],
    link: "https://counterrec.com/careers",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "Food Delivery",
    type: "Contract",
    location: "Bangalore",
    experience: "Fresher",
    education: "10th Grade",
    companyName: "Swiggy",
    companyUrl: "swiggy.com",
    salary: "Rs.9000 - Rs.25000",
    skills: ["Communication", "Driving"],
    link: "https://swiggy.com/careers",
  },
  {
    id: 4,
    postedOn: new Date(),
    title: "IT Support",
    type: "Full time",
    location: "Hyderabad",
    experience: "1-2 Years",
    education: "Graduation",
    companyName: "SoftCake",
    companyUrl: "softcake.com",
    salary: "Rs.25000 - Rs.45800",
    skills: ["Communication", "SQL", "Testing"],
    link: "https://softcake.com/careers",
  },
  {
    id: 5,
    postedOn: new Date(),
    title: "Branch Relationship Executive",
    type: "Full time",
    location: "Noida",
    experience: "Fresher",
    education: "12th Grade",
    companyName: "Dhanda Bank",
    companyUrl: "dhandabank.com",
    salary: "Rs.14500 - Rs.29100",
    skills: ["Communication", "Sales", "Marketing"],
    link: "https://dhandabank.com/careers",
  },
];
